# Generated by Django 6.0.6 on 2026-06-23 05:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodingQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('Input', models.TextField()),
                ('Output', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('mcq_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('option1', models.CharField(max_length=200)),
                ('option2', models.CharField(max_length=200)),
                ('option3', models.CharField(max_length=200)),
                ('option4', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('education', models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('PhD', 'PhD')], max_length=100)),
                ('branch', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('CIVIL', 'CIVIL'), ('MECHANICAL', 'MECHANICAL')], max_length=100)),
                ('college_name', models.CharField(choices=[('VISWAM', 'VISWAM'), ('MITS', 'MITS'), ('ADITYA', 'ADITYA'), ('GVICS', 'GVICS')], max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date_of_birth', models.DateField()),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('mcq_test', models.BooleanField(default=True)),
                ('coding_test', models.BooleanField(default=True)),
                ('mcq_marks', models.IntegerField(default=0)),
                ('coding_marks', models.IntegerField(default=0)),
                ('total_marks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test_input', models.TextField()),
                ('expected_output', models.TextField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackthon_app.codingquestion')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='hackthon_app.user')),
            ],
        ),
    ]
