# Generated by Django 6.0.6 on 2026-06-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackthon_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='code',
            field=models.TextField(blank=True),
        ),
    ]
