# Generated by Django 6.0.6 on 2026-06-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackthon_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodingTest',
        ),
        migrations.AddField(
            model_name='user',
            name='coding_test',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mcq_test',
            field=models.BooleanField(default=True),
        ),
    ]
