# Generated by Django 6.0.6 on 2026-06-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackthon_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingtest',
            name='coding_id',
            field=models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='mcq_id',
            field=models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
