# Generated by Django 6.1 on 2026-08-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackthon_app', '0002_mcq_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='mcq_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
