# Generated by Django 6.0.6 on 2026-06-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackthon_app', '0002_alter_codingtest_coding_id_alter_mcq_mcq_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingtest',
            name='coding_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='mcq_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
