# Generated by Django 6.0.6 on 2026-06-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackthon_app', '0003_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
