# Generated by Django 6.1 on 2026-08-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackthon_app', '0003_alter_mcq_mcq_id_alter_testcase_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='mcq_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
