# Generated by Django 6.0.6 on 2026-06-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackthon_app', '0003_codingquestion_testcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coding_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='mcq_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Marks',
        ),
    ]
