# Generated by Django 6.0.6 on 2026-06-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackthon_app', '0004_alter_test_end_time_alter_test_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mcq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_1', models.CharField(max_length=10)),
                ('option_2', models.CharField(max_length=10)),
                ('option_3', models.CharField(max_length=10)),
                ('option_4', models.CharField(max_length=10)),
            ],
        ),
    ]
