# Generated by Django 6.0.6 on 2026-06-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackthon_app', '0005_mcq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='option_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='option_2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='option_3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='option_4',
            field=models.CharField(max_length=100),
        ),
    ]
