# Generated by Django 6.0.6 on 2026-06-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackthon_app', '0006_alter_mcq_option_1_alter_mcq_option_2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mcq',
        ),
        migrations.RemoveField(
            model_name='user',
            name='confirm_password',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
