# Generated by Django 6.0.6 on 2026-06-16 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackthon_app', '0007_delete_mcq_remove_user_confirm_password_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='hackthon_app.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
