# Generated by Django 6.0.6 on 2026-06-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackthon_app', '0009_mcq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
